export const en = {
  appTitle: "MediScan",
  tagline: "Fresh start prototype",
  environment: "Env",
  language: "Lang",
  lastRefresh: "Last refresh",
  daily: "Daily",
  weekly: "Weekly",
  highlightsTitle: "Today — Highlights",
  clinicalTrialsTitle: "Clinical Trials",
  latestResearchTitle: "Latest Research",
  costsInsuranceTitle: "Costs & Insurance",
  save: "Save",
  citations: "Citations",
  exportCosts: "Export costs report",
  profileTitle: "Your Profile",
  diseaseProfile: "Disease Profile",
  notifications: "Notifications",
  languageLabel: "Language",
  watchlistTitle: "Watchlist",
  disclaimerTitle: "Disclaimer",
  disclaimer1: "Educational prototype only. Not medical advice.",
  disclaimer2: "Replace with your privacy and sourcing policy.",
  global: "Global",
  eu: "EU",
  us: "US",
  en: "EN",
  th: "TH"
} as const;
