export const th = {
  appTitle: "มีดิสแกน",
  tagline: "ต้นแบบเริ่มใหม่",
  environment: "สภาพแวดล้อม",
  language: "ภาษา",
  lastRefresh: "อัปเดตล่าสุด",
  daily: "รายวัน",
  weekly: "รายสัปดาห์",
  highlightsTitle: "วันนี้ — ไฮไลต์",
  clinicalTrialsTitle: "การทดลองทางคลินิก",
  latestResearchTitle: "งานวิจัยล่าสุด",
  costsInsuranceTitle: "ค่าใช้จ่ายและประกัน",
  save: "บันทึก",
  citations: "แหล่งข้อมูล",
  exportCosts: "ส่งออกรายงานค่าใช้จ่าย",
  profileTitle: "โปรไฟล์ของคุณ",
  diseaseProfile: "โปรไฟล์โรค",
  notifications: "การแจ้งเตือน",
  languageLabel: "ภาษา",
  watchlistTitle: "รายการเฝ้าดู",
  disclaimerTitle: "ข้อจำกัดความรับผิด",
  disclaimer1: "ต้นแบบเพื่อการศึกษา ไม่ใช่คำแนะนำทางการแพทย์",
  disclaimer2: "แทนที่ด้วยนโยบายความเป็นส่วนตัวและแหล่งข้อมูลของคุณ",
  global: "ทั่วโลก",
  eu: "สหภาพยุโรป",
  us: "สหรัฐอเมริกา",
  en: "อังกฤษ",
  th: "ไทย"
} as const;
